[ubuntu]
ubuntu-node1 ansible_host=3.89.156.183 ansible_user=ubuntu ansible_ssh_private_key_file=/home/devashish/mykey.pem
ubuntu-node2 ansible_host=3.95.242.31 ansible_user=ubuntu ansible_ssh_private_key_file=/home/devashish/mykey.pem

[all_targets:children]
ubuntu
