#!/bin/bash

cmd=$1
file=$2

case "$cmd" in

addLineTop)
    line="$3"
    sed -i "1i $line" "$file"
    ;;

addLineBottom)
    line="$3"
    echo "$line" >> "$file"
    ;;

addLineAt)
    lineno="$3"
    line="$4"
    sed -i "${lineno}i $line" "$file"
    ;;

updateFirstWord)
    old="$3"
    new="$4"
    sed -i "0,/$old/s//$new/" "$file"
    ;;

updateAllWords)
    old="$3"
    new="$4"
    sed -i "s/$old/$new/g" "$file"
    ;;

insertWord)
    word1="$3"
    word2="$4"
    insert="$5"
    sed -i "s/$word1 $word2/$word1 $insert $word2/g" "$file"
    ;;

deleteLine)
    lineno="$3"
    sed -i "${lineno}d" "$file"
    ;;

deleteLineWord)
    word="$3"
    sed -i "/$word/d" "$file"
    ;;

*)
    echo "Invalid Command"
    ;;
esac